name: CI
on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - "public/**"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "src/**"
      - "public/**"
      - ".github/workflows/ci.yml"
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: iffy/install-nim@v5

      - name: Install Dependencies
        run: |
          sudo apt install libsass-dev sqlite3
          git submodule update --init --recursive
          nimble install kdl
          nimble install -d -y

      - name: Frontend
        run: nimble htmlpage

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu
          path: |
            dist
          if-no-files-found: error

  # windows:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: iffy/install-nim@v5

  #     - name: Install Dependencies
  #       run: |
  #         nimble install -d -y

  #     - name: Frontend
  #       run: nimble frontend

  #     - name: Backend
  #       run: nimble build

  #     - name: Upload Artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: windows
  #         path: |
  #           app.exe
  #           public
  #         if-no-files-found: error
